name: Daily FPL Video

on:
  schedule:
    - cron: '0 8 * * *'  # Runs every day at 08:00 UTC
  workflow_dispatch:     # Allows manual runs

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Write client_secret.json
        run: echo "${{ secrets.CLIENT_SECRET_JSON }}"  | base64 --decode > src/scripts/client_secret.json

      - name: Write oauth_token.json
        run: echo "${{ secrets.OAUTH_TOKEN_JSON }}"  | base64 --decode > src/scripts/token.json

      - name: Run daily video generation and upload
        run: npm run daily

      # Commit and Push price changes only if video generation is successful
      - name: Commit and Push price changes
        if: success()  # Only run this step if the previous steps were successful
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Stage the updated files
          git add public/assets/price-changes.json src/data/yesterday-players.json

          # Commit the changes
          git commit -m "Update FPL price changes"

          # Push the changes back to the repository
          git push origin main  # Replace 'main' with the appropriate branch name if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}